name: beautify
markdown: maruku
pygments: false

baseurl: http://beautify.io

debug: false

exclude: [README.md, bootstrap, build.sh, less, style.less, scripts]

authors:
    ceberhardt:
        name: Colin Eberhardt
        gravatar: 458f2e0d08d4114f8b323798cfea141d
        author-summary: A coding addict, dividing my time between iOS, C#, JavaScript and everything else. <br/><br/><a href="https://twitter.com/ColinEberhardt">@ColinEberhardt</a> <a href="https://plus.google.com/u/0/104181672098184856535" rel="author">Google+</a>.
    godds:
        name: Graham Odds
        gravatar: 3f5e6c753071c6a41f7f1dbb89daeb3b
        author-summary: Designer and developer working across desktop, web and mobile, with a particular taste for data visualisation.<br/><br/><a href="https://twitter.com/g_odds">@g_odds</a><br/><a href="https://plus.google.com/u/0/106838695703708413394" rel="author">Google+</a>
    cgrant:
        name: Chris Grant
        gravatar: 7ed1a4b5f686f58db97862a26d38d30f
        author-summary: iOS expert and technical lead behind the open-source <a href="https://github.com/beautify/beautify-ios">beautify-ios</a> framework. <br/><br/><a href="https://twitter.com/christhegrant">@christhegrant</a>
    sduncan:
        name: Simon Duncan
        gravatar: 0f765c3e99ff8441cf0d0f60aed9634b
        author-summary: UX designer. Arduino & physical computing enthusiest. Likes hip hop and 30 minute drone pieces.<br/><br/><a href="https://twitter.com/simonduncan">@simonduncan</a>